service:
  name: aws-lambda-nodejs-no-framework-service

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod # Set the default stage used. Default is dev
  region: us-east-1 # Overwrite the default region used. Default is us-east-1
  memorySize: 128 # Overwrite the default memory size. Default is 1024
  timeout: 10 # in seconds
  environment: # service wide environment variables
    serviceEnvVar: 123456789-service

functions:
  pingFunction: # A Function
    handler: handler.pingHandler # The file and module for this specific function.
    description: Ping pong function # The description of your function.
    runtime: nodejs8.10 # Runtime for this specific function. Overrides the default which is set on the provider level
    memorySize: 128 # memorySize for this specific function.
    timeout: 6 # Timeout for this specific function.  Overrides the default set above
    environment: # Function level environment variables
      functionEnvVar: 123456789-fn
    events: # The Events that trigger this Function
      - http: # This creates an API Gateway HTTP endpoint which can be used to trigger this function.
          path: ping # Path for this endpoint
          method: get # HTTP method for this endpoint
