service: aws-java-simple-http-endpoint

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8

package:
  artifact: target/aws-lambda-java-no-framework.jar

functions:
  pingFunction:
    handler: com.serverless.PingHandler
    events:
      - http:
          path: ping
          method: get
